# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobshow', '0007_remove_bob_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bob',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
